menu:
  # Archives: /archives
  # MDZZ: /favourite
  时光机: /story
  关于我: /aboutme

rss: /atom.xml

description: 

social:
  weibo: http://weibo.cn/onlychacha
  github: https://github.com/Lotheve
  stack_overflow: 
  facebook: 
  twitter: 
  google_plus: 

page_comment: true

logo: /images/avatar.jpg
background:
  cover: /images/background-cover.jpg
  color: cover-purple

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: 

google_analytics: UA-78918255-1
baidu_tongji: 9cdad07c755fa23f6aced510c6760e87
favicon: /images/avatar.jpeg

#mathjax
mathjax: true