menu:
  # Archives: /archives
  # MDZZ: /favourite
  时光机: /story
  关于我: /aboutme

rss: /atom.xml

description: 

social:
  weibo: http://weibo.cn/onlychacha
  github: https://github.com/Lotheve
  stack_overflow: 
  facebook: 
  twitter: 
  google_plus: 

page_comment: true

logo: /images/avatar.jpg
background:
  cover: /images/background-cover.jpg
  color: cover-purple

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: 

google_analytics: UA-104179898-1
baidu_tongji: 625528118da5bf56aa02dc2a21537069

favicon: /images/avatar.jpeg

#mathjax
mathjax: true